
# Import routes from annotations in controllers.
# Documentation on this feature can be found here:
# http://symfony.com/doc/current/bundles/SensioFrameworkExtraBundle/annotations/routing.html
ldi_project_hub_controller_routes:
    resource: "@LDIProjectHubBundle/Controller"
    type:     annotation

# Set sensible defaults if controller routes fail.
# 
# Note: The Symfony router will always choose the first matching route it finds,
# thus these routes will only activate if not present in the controller.
ldi_project_hub_homepage:
    pattern:  /
    defaults: { _controller: LDIProjectHubBundle:Default:index }
