ldi_project_hub_homepage:
    pattern:  /
    defaults: { _controller: LDIProjectHubBundle:Default:index }

ldi_project_hub_new:
    pattern: /
    defaults: { _controller: LDIProjectHubBundle:user:create }
