<?php

namespace LDI\ProjectHubBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * discussionPostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DiscussionPostRepository extends EntityRepository
{
}
